### ISSUE TITLE
New User algorithm undercounts new users

### ISSUE THREAD

**Issue by fbertsch** [mozilla/Fx_Usage_Report#44]
Currently the algorithm is:

1. Calculate beginning and end of the previous week
2. Filter out `submission_date_s3`s that fall outside of this range
3. Filter out `profile_creation_date`s that fall outside of this range

The problem with this approach is that it leaves out any users who start in week 1 but submit their first ping in week 2. This could be especially prevalent for `new_users` who submit data on the last day of the week.

For example, consider a user living in the US who starts using on Saturday. We timestamp the end of the week as Sunday 00:00 UTC. So if this user submits their first ping at the end of their first day, e.g. after 17:00 CST, then that ping will be considered submitted on the "next" week, and will then not be included in any analysis:
- It will not be included in this week's analysis because of condition (2.)
- It will not be included in next week's analysis because of condition (3.)

*If* we are going to be filtering on `submission_date_s3`, we have to determine the earliest `submission_date_s3` of the client, and use _that_ as an indication that they are a new user instead. Otherwise we will be undercounting new users.

**Comment by benmiroglio** [comment]
This is tricky, and I think we're going to have to accept some inaccuracy here. The algorithm will become increasingly expensive with time if we don't do some filtering by `submission_date_s3` upfront.

I looked into two alternative approaches for comparison:

Method 1:
1.  Calculate beginning and end of the previous week
2. Take the min `submission_date_s3` for each client across all dates
3.  Filter out any `submission_date_s3` minimums outside of the date range in (1)

Notes: Quite expensive and doesn't scale with time, but accurate

Method 2
1. Calculate beginning and end of the previous week
2. Filter out any `submission_date_s3`s older than 35 days from the end of the previous week
3. Filter out any `profile_creation_date`s older than 35 days from the end of the previous week
4. Take the min `submission_date_s3` for each client across all dates
5. Filter out any `submission_date_s3` minimums outside of the date range in (i)

Notes: Cheap and scales with time, ignores clients who created a profile >35 days ago that have yet to send their first ping which ends up being ~0.9%, which seems very high.

Here are the resulting percentages of new users over 7 days in March using the original method, method 1 and method 2.

![image](https://user-images.githubusercontent.com/8593945/37989416-3f75d5c4-31b8-11e8-8789-a25c32e83d8c.png)


Curious to hear from @fbertsch and @SuYoungHong on this. I suspect the bulk of the 0.9% of clients who submit their first ping a month after profile creation are victims of client clock issues or something else wonky.

Ping if you're interested in seeing the notebook I used for this analysis.

**Comment by fbertsch** [comment]
.9% of all clients being new clients who are reporting their first ping 35 days later is outrageously high. That is ~17% of all new clients!

@benmiroglio can you email us the notebook?

**Comment by fbertsch** [comment]
@benmiroglio it would be helpful to get a similar analysis: a plot of, given that we include only the most recent N days in determining new users (where your example is 35), what % of new_users that encompasses. The plot would be `% of New Users` on the Y axis, and `Number of Days Included` on the X axis. You could just choose some arbitrary time period to run it on

**Comment by benmiroglio** [comment]
email sent

And I can do that, 35 seemed sufficiently high when framing the problem, but I agree it'd be interesting to see how this changes given the preliminary result.

**Comment by benmiroglio** [comment]
Here is that plot you requested @fbertsch (which includes release, beta, esr and "other" channels). It is quite daunting. In peaking at the data, there are numerous cases where a profile has a pcd multiple years ago, however the first ping we see is in late March 2018. I will highlight these cases and send over a notebook shortly.

![image](https://user-images.githubusercontent.com/8593945/38049878-336aac66-327e-11e8-8c23-a5e52ce09d6f.png)

The questions we should consider:
* those users really "new"?
    + is their pcd accurate?
    + are we missing pings from these users?

**Comment by benmiroglio** [comment]
The stats that support the above graph are being investigated further in [Bug 1449739](https://bugzilla.mozilla.org/show_bug.cgi?id=1449739).

**Comment by SuYoungHong** [comment]
issue has been moved to bugs
resolved for this project
