### ISSUE TITLE
Consider adding forecasting trendlines to hardware graphs

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/Fx_Usage_Report#59]
It may be interesting to forecast out say 1 year (or whatever we feel is comfortable given the data) into the future to see how things may change that we might want to be prepared for, or just for informational purposes. 

This would mostly be useful for the hardware report I think, as it's more about where the market is headed. 

For example if we look at display resolution, it looks like 1080p will take over as the primary display size in ~6 months. Or that users with < 4gb of ram will be rare in ~2 years. Or that Windows 10 will be the primary OS by the end of this year

**Comment by SuYoungHong** [comment]
Hi Stuart! Good suggestion. I'll discuss it with my team but with reporting this kind of data, extrapolating into the future can be a slippery slope and there could be a danger with the public mis-understanding what part of the data is conjecture and reporting. 

For the future, we're going to move these kind of discussions to the discourse topic: 

https://waffle.io/mozilla/firefox-hardware-report 

or the IRC chat: #datareport

so I'm gonna close this issue for now, but lets definitely continue this convo in one of the two discussion-forums!

- Su
