### ISSUE TITLE
Top add-ons percentages

### ISSUE THREAD

**Issue by da2x** [mozilla/Fx_Usage_Report#61]
Are the percentages of total Firefox users? or is it the percentage out of users who have any add-ons installed?

https://data.firefox.com/dashboard/usage-behavior#metric-overview-4

**Comment by SuYoungHong** [comment]
Hi da2x! Good question. The percentages for top addons is the % of all users for that group (including users who don't have addons). Hope that helps. 

FYI, we're moving questions and discussions over to the IRC chat and the discourse topic: 

IRC channel: #datareport
discourse topic: https://discourse.mozilla.org/c/fx-public-data

Feel free to ask more questions or open up more discussions in either of those two forums!

- Su
