### ISSUE TITLE
Questions about GPU models

### ISSUE THREAD

**Issue by openjck** [mozilla/Fx_Usage_Report#88]
I have a couple of questions about GPU models that we see in the data.

1. What is the difference between `gpuModel_Other` and `gpuModel_Unknown`? Would it be inaccurate to call these both "Other" in the front-end?
2. Do you have any insight into what `gpuModel_CIK-MULLINS`, `gpuModel_CIK-KABINI`, or `gpuModel_R600-RS880` represent? It looks like the first two are AMD GPUs and the third is an ATI GPU, but I'm not exactly sure how to turn them into human-readable names. I'm continuing to look into this but will take any advice you have.

**Comment by openjck** [comment]
As an alternative to question \#2, does Fx_Usage_Report have any access to more human-readable versions of GPU names? It would be a godsend if it could use those instead of codenames in the data, as mapping codenames to human-readable names after-the-fact is tricky, as it is in this case.

**Comment by akkomar** [comment]
`gpuModel_Other` are models that showed up in <1% of population, `gpuModel_Unknown` are cases where we don't have the mapping from an id.
Hardware report ETL is now being worked on in https://github.com/mozilla/firefox-public-data-report-etl/pull/1. In this new implementation we won't keep this distinction and mark both cases as `Other` - this will be consistent with the way we currently handle GPU vendor names.

**Comment by openjck** [comment]
Sounds good. It looks like this is already being done. Is that correct? If so, feel free to close this issue.

**Comment by openjck** [comment]
Unless you happen to have any insight into question 2.

**Comment by openjck** [comment]
Actually, of those GPU models mentioned in question 2, only *CIK-KABINI* remains in this dataset. Maybe it's not terrible to leave that as-is in the front-end.

It looks like *CIK-KABINI* may be part of AMD's *Radeon HD 8000* series, but it's not the only chipset in that series, so it seems it would be inaccurate to rename *CIK-KABINI* to *Radeon HD 8000*.

**Comment by akkomar** [comment]
> Sounds good. It looks like this is already being done. Is that correct? If so, feel free to close this issue.

Yes, it has been implemented in https://github.com/mozilla/firefox-public-data-report-etl/pull/1

I'm not very familiar with the GPU mappings, I'd suggest we open a new issue in https://github.com/mozilla/firefox-public-data-report-etl and look into this when we migrate. I'll close this now.
