### ISSUE TITLE
Consider outputting all Darwin versions, even below 1%

### ISSUE THREAD

**Issue by openjck** [mozilla/Fx_Usage_Report#89]
This job appears to exclude any metric which has a value below 1%. Because of this, only one Darwin 18 metric is currently present in the dataset: `osName_Darwin-18.7.0`. Earlier versions like `osName_Darwin-18.6.0` and `osName_Darwin-18.5.0` do not appear.

Nonetheless, I group all metrics beginning with `osName_Darwin-18` into a bucket called "macOS Mojave" on the front-end, which is really inaccurate. The true Mojave total should be the sum of `osName_Darwin-18.7.0`, `osName_Darwin-18.6.0`, `osName_Darwin-18.5.0`, etc. But only the first of those metrics currently appears in the dataset.

Would it be possible to provide metrics for all versions of Darwin, even those below 1%? That would allow me to provide accurate numbers for major Mac releases like Mojave, High Sierra, etc. Alternatively, maybe this job could do the grouping right here. Rather than outputting `osName_Darwin-18.[1,2,3,4,5,6,7,etc.].0`, it could output `osName_Darwin-Mojave`.

**Comment by openjck** [comment]
A note to myself: I may want to revert these commits depending on the resolution here:

* https://github.com/mozilla/ensemble-transposer/commit/ebb779beeb16563375085c19cf4e49976bac08f5
* https://github.com/mozilla/ensemble-transposer/commit/1840a7f830e260d8ebd7de81366c1f5942143c7f

**Comment by akkomar** [comment]
Hardware report ETL is now being worked on in https://github.com/mozilla/firefox-public-data-report-etl/pull/1. As discussed on Slack, we'll group Darwin and Linux versions by major number.

**Comment by openjck** [comment]
Does this mean point releases will never appear in the dataset? For example, will we see Darwin-19.0.0 but never Darwin-19.1.0 in the dataset? Will Darwin-19.0.0 be a total of all Darwin-19.x.x counts?

**Comment by openjck** [comment]
Relatedly, by any chance, do you have an automated method of mapping versions to their human-readable names? e.g., Darwin-19.x.x = Catalina

I've been doing that mapping manually, which is fine, but if there's an automated way of doing that, even better.

**Comment by akkomar** [comment]
> Does this mean point releases will never appear in the dataset? For example, will we see Darwin-19.0.0 but never Darwin-19.1.0 in the dataset? Will Darwin-19.0.0 be a total of all Darwin-19.x.x counts?

They'll be merged under the major number, so both Darwin-19.0.0 and Darwin-19.1.0 are aggregated under Darwin-19.x


> Relatedly, by any chance, do you have an automated method of mapping versions to their human-readable names? e.g., Darwin-19.x.x = Catalina
> 
> I've been doing that mapping manually, which is fine, but if there's an automated way of doing that, even better.

Not really. I quickly looked at this and can't see other way than hardcoding [these mappings](https://en.wikipedia.org/wiki/Darwin_(operating_system)#Release_history) somewhere.

**Comment by openjck** [comment]
That works! Let me know when that work is done and you are outputting labels like Darwin-19.x. I'll update my ETL job to give those human-readable names.

**Comment by openjck** [comment]
Arkadiusz let me know on Slack that these are already in the dataset, so I'm happy. Feel free to close.
